server:
  address: localhost
  port: 8089

spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/test_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: "root"
    password: "test1234"
    hikari:
      pool-name: TestHikariCp-Pool
      maximum-pool-size: 10
      connection-timeout: 30000
      connection-init-sql: SELECT 1
      minimum-idle: 10
      max-lifetime: 1800000
      idle-timeout: 600000
      auto-commit: false
      validation-timeout: 2000

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true