server:
  address: localhost
  port: 8089

spring:
  profiles:
    active: local

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.driver
      jdbc-url: jdbc:mysql://localhost:3306/test_db?serverTimezone=UTC&characterEncoding=UTF-8
      username: "root"
      password: "test1234"
      pool-name: TestHikariCp-Pool
      maximum-pool-size: 10
      max-lifetime: 1800000
      auto-commit: false
      connection-timeout: 30000


  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true